### ISSUE TITLE
Error while attempting to filter via radio buttons

### ISSUE THREAD

**Issue by kushalbakshi** [datajoint/sci-viz#63]
This error occurs while attempting to filters entries in a table component via the drop-down radio buttons. Currently, none of the columns are able to filter with these radio buttons. Below are two error stacks for two different columns in the table: 

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/pharus/dynamic_api.py", line 45, in subjecttableattributes
    return component_instance.attributes_route()
  File "/opt/conda/lib/python3.8/site-packages/pharus/component_interface.py", line 335, in attributes_route
    attributes_meta = _DJConnector._get_attributes(
  File "/opt/conda/lib/python3.8/site-packages/pharus/interface.py", line 238, in _get_attributes
    for (v,) in (dj.U(attribute_name) & query).fetch()
  File "/opt/conda/lib/python3.8/site-packages/datajoint/fetch.py", line 256, in __call__
    cur = self._expression.cursor(
  File "/opt/conda/lib/python3.8/site-packages/datajoint/expression.py", line 629, in cursor
    return self.connection.query(sql, as_dict=as_dict)
  File "/opt/conda/lib/python3.8/site-packages/datajoint/connection.py", line 340, in query
    self._execute_query(cursor, query, args, suppress_warnings)
  File "/opt/conda/lib/python3.8/site-packages/datajoint/connection.py", line 296, in _execute_query
    raise translate_query_error(err, query)
datajoint.errors.UnknownAttributeError: Unknown column 'sex' in 'having clause'
```

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/pharus/dynamic_api.py", line 45, in subjecttableattributes
    return component_instance.attributes_route()
  File "/opt/conda/lib/python3.8/site-packages/pharus/component_interface.py", line 335, in attributes_route
    attributes_meta = _DJConnector._get_attributes(
  File "/opt/conda/lib/python3.8/site-packages/pharus/interface.py", line 238, in _get_attributes
    for (v,) in (dj.U(attribute_name) & query).fetch()
  File "/opt/conda/lib/python3.8/site-packages/datajoint/fetch.py", line 256, in __call__
    cur = self._expression.cursor(
  File "/opt/conda/lib/python3.8/site-packages/datajoint/expression.py", line 629, in cursor
    return self.connection.query(sql, as_dict=as_dict)
  File "/opt/conda/lib/python3.8/site-packages/datajoint/connection.py", line 340, in query
    self._execute_query(cursor, query, args, suppress_warnings)
  File "/opt/conda/lib/python3.8/site-packages/datajoint/connection.py", line 296, in _execute_query
    raise translate_query_error(err, query)
datajoint.errors.UnknownAttributeError: Unknown column 'mlims_name' in 'having clause'
```

Here is the screenshot of the webpage when the filtering is attempted: 
![image](https://user-images.githubusercontent.com/52367253/215831720-7a5fd47a-d9e7-45c7-8baa-07a8ef3d45e9.png)

**Comment by guzman-raphael** [comment]
@kushalbakshi Could you provide a minimal example schema and spec that results in this error?

**Comment by kushalbakshi** [comment]
The spec sheet is [here](https://github.com/dj-sciops/nyu_sippylab/blob/main/webapps/sciviz/sippylab_specsheet.yaml) and the schema are in the corresponding pipeline [here](https://github.com/dj-sciops/nyu_sippylab/blob/main/workflow/pipeline/lab.py). This table view calls `lab.Subject`. There are currently two test entries and ~10 entries ingested from the lab's animal colony management database.
